services:
    # server:
    #     build:
    #         context: .
    #     environment:
    #         NODE_ENV: production
    #     ports:
    #         - 3000:3000

    #     depends_on:
    #         db:
    #             condition: service_healthy
    db:
      build:
        dockerfile: database.Dockerfile
      env_file:
        - .env
      ports:
        - 5432:5432
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "main"]
        interval: 10s
        timeout: 5s
        retries: 5